[WIP] Update readme for the repo
netlify/code-examples pull request #4
Opened 2018-04-26 17:09 UTC by lunaceee

2018-05-04 17:41 UTC, verythorough requested changes
I'm glad you're looking at these and testing them out! I made a few suggestions for improving the content.

2018-05-04 17:41 UTC, verythorough commented on README.md
> +Code snippets for you to get started with Netlify features.
I think this page should include a little more guidance for the reader - links to each folder, or at least an explanation that each folder contains another example with a readme of its own. (Right now the list would have only one item - the function_examples folder, but that's OK.)

2018-05-04 17:41 UTC, verythorough commented on function_examples/README.md
> +To help you quickly get started, we created several simple code examples under `functions_examples` folder to showcase the basic usage of Netlify Functions. Detailed instructions enclosed under each
This readme is in the `function_examples` folder already, so I don't think this explanation is necessary. Instead, I would make a list of links to each subfolder, with the name and a very short description of the sample's key programming characteristics. For example:

- [Random Word](/random-word): a very basic function with no dependencies or build tools
- [Use Env](/use-env): function that uses Netlify build environment variables, with no dependencies or build tools
- [Rest](/rest): function for calling an external API with `node-fetch`, using `netlify-lambda` to bundle dependencies
- [Token Hider](/token-hider): function using `axios` to access an external API, using Netlify build environment variables to hide the API token; bundled with `netlify-lambda`

2018-05-04 17:41 UTC, verythorough commented on function_examples/random-word/README.md
> +This is a basic example of a function that when it gets called, returns a random word from an array of words back. This function has no build process and does not use any external packages.
I would add that the function itself is stored in `/functions`, and the page with a link that calls the function is in `/_site`. I assume @futuregerald also made a demo site with this page, so I would link that so people can see how it works.

2018-05-04 17:41 UTC, verythorough commented on function_examples/rest/README.md
> +This function gets data from https://jsonplaceholder.typicode.com/, and also has a build process.
I would say that netlify-lambda is what's being used for the build process, and that it takes the source files and package.json from `/func` and builds the function as a single file in a new folder, `/functions`. I would link to netlify-lambda for further information on local serving, build commands, etc.

2018-05-04 17:41 UTC, verythorough commented on function_examples/token-hider/README.md
> +
Something is wrong with this line. I think some explanatory text may have been accidentally removed at some point. I'd check with @depadiernos to see what his intention was here.

2018-05-04 17:41 UTC, verythorough commented on function_examples/token-hider/README.md
> +_Notes: Make sure you run Functions first before you run the site._
This is included in step 2 (line 23), but something weird with formatting combined the command with some variables. When Step 2 is fixed, I don't think this line will be necessary.

2018-05-04 17:41 UTC, verythorough commented on function_examples/token-hider/README.md
> +
(I'm guessing that at some point there was a step to add those two variables to a `.env` file before running the `npm run lambda:dev` line at the end of the line.)

2018-05-04 17:41 UTC, verythorough commented on function_examples/use-env/README.md
> +_at this moment you can only use variables specified in the UI and not in netlify.toml_
Capitalize the `a` at the beginning and add a period at the end.

Also, this may no longer be true. @calavera could probably confirm.

2018-05-09 20:45 UTC, verythorough commented on function_examples/token-hider/README.md
> +
I didn't realize this command would work! I think it's worth telling the reader to run these lines in the command line.

2018-05-09 21:04 UTC, verythorough approved these changes

2018-05-10 19:48 UTC, lunaceee commented
I've updated the files based on your review @verythorough . Let me know if it looks good to you. Thanks!

2018-05-16 20:40 UTC, merged